Repository Varenthein/WDP-2001-03, pull requests merged in 2020-02, with the labels that each got.

#33 WDP200103-35
  README.md
Labels: documentation, review needed

#34 WDP200103-37
  README.md
Labels: documentation, review needed

#28 Wdp200103 21
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/common/ProductBox/ProductBoxContainer.js
  src/redux/initialState.js
  src/redux/productsRedux.js
  yarn.lock
Labels: review needed

#31 WDP200103-29
  package.json
  src/components/features/Gallery/Gallery.js
  src/components/features/Gallery/Gallery.module.scss
  src/components/features/Gallery/GalleryContainer.js
  yarn.lock
Labels: review needed

#36 WDP200103-41
  src/components/common/Breadcrumb/Breadcrumb.js
  src/components/common/Breadcrumb/Breadcrumb.module.scss
  src/components/common/Breadcrumb/BreadcrumbItem.js
  src/components/common/Breadcrumb/BreadcrumbSeparator.js
  src/components/layout/Banner/Banner.js
  src/components/layout/Banner/Banner.module.scss
  src/components/views/ProductList/ProductList.js
Labels: review needed

#38 Wdp200103 38
  src/components/common/PopUp/PopUp.js
  src/components/common/PopUp/PopUp.module.scss
  src/components/layout/MainLayout/MainLayout.js
  src/styles/settings.scss
Labels: review needed

#39 WDP200103-34
  src/components/layout/Feedback/Feedback.js
Labels: review needed

#40 WDP200103-42
  src/components/features/Show/Show.js
  src/components/features/SortBy/SortBy.js
  src/components/features/ViewOptions/ViewOption.js
  src/components/features/ViewOptions/ViewOption.module.scss
  src/components/views/ProductList/ProductList.js
  src/components/views/ProductList/ProductList.module.scss
Labels: review needed

#37 WDP200103-42
  src/components/features/Show/Show.js
  src/components/features/Show/Show.module.scss
  src/components/features/SortBy/SortBy.js
  src/components/features/SortBy/SortBy.modules.scss
  src/components/layout/MenuBar/MenuBar.js
  src/components/views/ProductList/ProductList.js
  src/components/views/ProductList/ProductList.module.scss
Labels: requested changes

#43 Wdp200103 13 v2
  src/components/features/NewFurniture/NewFurniture.js
  src/components/features/NewFurniture/NewFurniture.module.scss
  src/components/features/Swipe/Swipe.js
  src/components/features/Swipe/Swipe.module.scss
  src/components/features/Swipe/SwipeContainer.js
Labels: review needed

#14 WDP200103-14
  package-lock.json
  package.json
  src/components/features/ProductSearch/ProductSearch.js
  src/components/features/ProductSearch/ProductSearch.module.scss
  src/components/features/ProductSearch/ProductSearch.test.js
  src/components/features/Promotion/Promotion.js
  src/components/layout/MenuBar/MenuBar.js
  src/components/layout/MenuBar/MenuBar.module.scss
  src/components/layout/MenuBar/MenuBar.test.js
Labels: review needed

#47 Wdp200103 47
  package-lock.json
  package.json
  src/components/common/ProductBox/ProductBox.js
  src/components/common/ProductBox/ProductBox.module.scss
  src/components/common/ProductBox/ProductBoxContainer.js
  src/components/features/FilterByCategories/FilterByCategories.js
  src/components/features/FilterByCategories/FilterByCategories.module.scss
  src/components/features/FilterByCategories/FilterByCategoriesContainer.js
  src/components/features/FilterByPrice/FilterByPrice.js
  src/components/features/FilterByPrice/FilterByPrice.module.scss
  src/components/features/Gallery/Gallery.js
  src/components/features/Gallery/Gallery.module.scss
  src/components/features/Gallery/GalleryContainer.js
  src/components/features/Sale/Sale.js
  src/components/features/Sale/Sale.module.scss
  src/components/features/SliderFilter/SliderFilter.js
  src/components/features/SliderFilter/SliderFilterComponents.js
  src/components/features/SliderFilter/stylespan.modules.scss
  src/components/layout/MenuBar/MenuBar.js
  src/components/layout/MenuBar/MenuBar.module.scss
  src/components/views/Homepage/Homepage.js
  src/components/views/ProductList/ProductList.js
  yarn.lock
Labels: review needed

#51 Wdp200103 48
  src/components/layout/MenuBar/MenuBar.js
Labels: review needed

#44 Wdp200103 45
  src/redux/filterByColorRedux.js
Labels: conflicted files

#53 Wdp200103 50
  src/components/features/FilterByTag/FilterByTag.js
  src/components/features/FilterByTag/FilterByTag.module.scss
  src/components/features/FilterByTag/FilterByTagContainer.js
  src/components/views/ProductList/ProductList.js
Labels: review needed
